/**
 * @license Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or https://ckeditor.com/license
 */

/**
 * This file was added automatically by CKEditor builder.
 * You may re-use it at any time to build CKEditor again.
 *
 * If you would like to build CKEditor online again
 * (for example to upgrade), visit one the following links:
 *
 * (1) https://ckeditor.com/cke4/builder
 *     Visit online builder to build CKEditor from scratch.
 *
 * (2) https://ckeditor.com/cke4/builder/a39322a30e2ca58becd776b3e564803e
 *     Visit online builder to build CKEditor, starting with the same setup as before.
 *
 * (3) https://ckeditor.com/cke4/builder/download/a39322a30e2ca58becd776b3e564803e
 *     Straight download link to the latest version of CKEditor (Optimized) with the same setup as before.
 *
 * NOTE:
 *    This file is not used by CKEditor, you may remove it.
 *    Changing this file will not change your CKEditor configuration.
 */

var CKBUILDER_CONFIG = {
	skin: 'moono-lisa',
	preset: 'full',
	ignore: [
		'.DS_Store',
		'.bender',
		'.editorconfig',
		'.gitattributes',
		'.gitignore',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'.mailmap',
		'.npm',
		'.travis.yml',
		'bender-err.log',
		'bender-out.log',
		'bender.ci.js',
		'bender.js',
		'dev',
		'gruntfile.js',
		'less',
		'node_modules',
		'package.json',
		'tests'
	],
	plugins : {
		'Audio' : 1,
		'FMathEditor' : 1,
		'MathEx' : 1,
		'N1ED' : 1,
		'OpenStreet' : 1,
		'SPImage' : 1,
		'SimpleImage' : 1,
		'SimpleLink' : 1,
		'Text2Speech' : 1,
		'a11ychecker' : 1,
		'a11yhelp' : 1,
		'about' : 1,
		'ajax' : 1,
		'allmedias' : 1,
		'allowsave' : 1,
		'api' : 1,
		'autocomplete' : 1,
		'autocorrect' : 1,
		'autoembed' : 1,
		'autogrow' : 1,
		'autoplaceholder' : 1,
		'autosave' : 1,
		'backgrounds' : 1,
		'backup' : 1,
		'balloontoolbar' : 1,
		'base64image' : 1,
		'basewidget' : 1,
		'basicstyles' : 1,
		'bbcode' : 1,
		'bgimage' : 1,
		'bidi' : 1,
		'block' : 1,
		'blockquote' : 1,
		'bootstrapTable' : 1,
		'bootstrapTabs' : 1,
		'bootstrapVisibility' : 1,
		'brclear' : 1,
		'browser' : 1,
		'btbutton' : 1,
		'btgrid' : 1,
		'btquicktable' : 1,
		'cavacnote' : 1,
		'ccmsacdc' : 1,
		'ccmsconfighelper' : 1,
		'ccmssourcedialog' : 1,
		'chart' : 1,
		'ckawesome' : 1,
		'ckeditor-gwf-plugin' : 1,
		'ckeditor_fa' : 1,
		'ckeditortablecellsselection' : 1,
		'ckwebspeech' : 1,
		'cleanuploader' : 1,
		'clipboard' : 1,
		'closebtn' : 1,
		'closedialogoutside' : 1,
		'cloudservices' : 1,
		'codeTag' : 1,
		'codemirror' : 1,
		'codesnippet' : 1,
		'codesnippetgeshi' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'computedfont' : 1,
		'computedstyles' : 1,
		'confighelper' : 1,
		'contents' : 1,
		'contextmenu' : 1,
		'copyformatting' : 1,
		'crossreference' : 1,
		'cssanim' : 1,
		'custimage' : 1,
		'deselect' : 1,
		'detail' : 1,
		'devtools' : 1,
		'dialogadvtab' : 1,
		'div' : 1,
		'divarea' : 1,
		'docfont' : 1,
		'dropdownmenumanager' : 1,
		'easyimage' : 1,
		'easykeymap' : 1,
		'elementspath' : 1,
		'embed' : 1,
		'embedsemantic' : 1,
		'emoji' : 1,
		'emojione' : 1,
		'enhancedcolorbuttton' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'eqneditor' : 1,
		'extraformattributes' : 1,
		'fastimage' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'fixed' : 1,
		'flash' : 1,
		'floating-tools' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'footnotes' : 1,
		'format' : 1,
		'format_buttons' : 1,
		'forms' : 1,
		'gallery' : 1,
		'gg' : 1,
		'glossary' : 1,
		'glyphicons' : 1,
		'googleDocPastePlugin' : 1,
		'googledocs' : 1,
		'googlesearch' : 1,
		'googlethisterm' : 1,
		'grid' : 1,
		'hkemoji' : 1,
		'hkurlsplit' : 1,
		'horizontalrule' : 1,
		'html5audio' : 1,
		'html5validation' : 1,
		'html5video' : 1,
		'htmlbuttons' : 1,
		'htmlwriter' : 1,
		'iframe' : 1,
		'iframedialog' : 1,
		'image' : 1,
		'image2' : 1,
		'imageCustomUploader' : 1,
		'imagebrowser' : 1,
		'imagepaste' : 1,
		'imageresize' : 1,
		'imageresizerowandcolumn' : 1,
		'imageresponsive' : 1,
		'imagerotate' : 1,
		'imageuploader' : 1,
		'imgbrowse' : 1,
		'imgupload' : 1,
		'imgur' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'inlinecancel' : 1,
		'inserthtml4x' : 1,
		'inserthtmlfile' : 1,
		'insertpre' : 1,
		'internallink' : 1,
		'justify' : 1,
		'label' : 1,
		'language' : 1,
		'layoutmanager' : 1,
		'leaflet' : 1,
		'letterspacing' : 1,
		'lightbox' : 1,
		'lineheight' : 1,
		'link' : 1,
		'linkayt' : 1,
		'list' : 1,
		'liststyle' : 1,
		'lite' : 1,
		'liveedit' : 1,
		'locationmap' : 1,
		'loremipsum' : 1,
		'magicline' : 1,
		'markdown' : 1,
		'mathedit' : 1,
		'mathjax' : 1,
		'maxheight' : 1,
		'maximize' : 1,
		'media' : 1,
		'mediabrowser' : 1,
		'mediaembed' : 1,
		'mentions' : 1,
		'mrmonkey' : 1,
		'nbsp' : 1,
		'newpage' : 1,
		'niftyimages' : 1,
		'niftytimers' : 1,
		'noabp' : 1,
		'numericinput' : 1,
		'oembed' : 1,
		'onchange' : 1,
		'openlink' : 1,
		'osem_googlemaps' : 1,
		'page2images' : 1,
		'pagebreak' : 1,
		'pasteFromGoogleDoc' : 1,
		'pastebase64' : 1,
		'pastecode' : 1,
		'pastefromexcel' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'pbckcode' : 1,
		'performx' : 1,
		'placeholder' : 1,
		'placeholder_select' : 1,
		'pre' : 1,
		'preview' : 1,
		'print' : 1,
		'prism' : 1,
		'qrc' : 1,
		'quicktable' : 1,
		'quote' : 1,
		'quran' : 1,
		'removeformat' : 1,
		'removespan' : 1,
		'replaceTagNameByBsquochoai' : 1,
		'resize' : 1,
		'resizewithwindow' : 1,
		'save' : 1,
		'save-to-pdf' : 1,
		'savemarkdown' : 1,
		'scayt' : 1,
		'scribens' : 1,
		'section' : 1,
		'selectall' : 1,
		'selectallcontextmenu' : 1,
		'sharedspace' : 1,
		'showblocks' : 1,
		'showborders' : 1,
		'showprotected' : 1,
		'simage' : 1,
		'simple-image-browser' : 1,
		'simple-ruler' : 1,
		'simpleImageUpload' : 1,
		'simplebutton' : 1,
		'sketchfab' : 1,
		'slideshow' : 1,
		'smallerselection' : 1,
		'smiley' : 1,
		'soundPlayer' : 1,
		'sourcearea' : 1,
		'sourcedialog' : 1,
		'spacingsliders' : 1,
		'specialchar' : 1,
		'spoiler' : 1,
		'stat' : 1,
		'staticspace' : 1,
		'strinsert' : 1,
		'stylescombo' : 1,
		'stylesheetparser' : 1,
		'stylesheetparser-fixed' : 1,
		'symbol' : 1,
		'syntaxhighlight' : 1,
		'tab' : 1,
		'tabbedimagebrowser' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tableresizerowandcolumn' : 1,
		'tableselection' : 1,
		'tablesorter' : 1,
		'tabletools' : 1,
		'tabletoolstoolbar' : 1,
		'tangy-checkbox' : 1,
		'tangy-gps' : 1,
		'tangy-input' : 1,
		'tangy-location' : 1,
		'templates' : 1,
		'textIdent' : 1,
//		'textindent' : 1,
		'textselection' : 1,
		'textsignature' : 1,
		'texttransform' : 1,
		'texzilla' : 1,
		'tliyoutube' : 1,
		'tliyoutube2' : 1,
		'toc' : 1,
		'token' : 1,
		'toolbar' : 1,
		'toolbarswitch' : 1,
		'tweetabletext' : 1,
		'uicolor' : 1,
		'undo' : 1,
		'uploadcare' : 1,
		'uploadfile' : 1,
		'uploadimage' : 1,
		'video' : 1,
		'videodetector' : 1,
		'videoembed' : 1,
		'videosnapshot' : 1,
		'wenzgmap' : 1,
		'widgetcontextmenu' : 1,
		'wlpheix' : 1,
		'wordcount' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1,
		'xdsoft_translater' : 1,
		'xmas' : 1,
		'xmltemplates' : 1,
		'yaqr' : 1,
		'youtube' : 1,
		'zamanager' : 1,
		'zoom' : 1,
		'zsuploader' : 1
	},
	languages : {
		'af' : 1,
		'ar' : 1,
		'az' : 1,
		'bg' : 1,
		'bn' : 1,
		'bs' : 1,
		'ca' : 1,
		'cs' : 1,
		'cy' : 1,
		'da' : 1,
		'de' : 1,
		'de-ch' : 1,
		'el' : 1,
		'en' : 1,
		'en-au' : 1,
		'en-ca' : 1,
		'en-gb' : 1,
		'eo' : 1,
		'es' : 1,
		'es-mx' : 1,
		'et' : 1,
		'eu' : 1,
		'fa' : 1,
		'fi' : 1,
		'fo' : 1,
		'fr' : 1,
		'fr-ca' : 1,
		'gl' : 1,
		'gu' : 1,
		'he' : 1,
		'hi' : 1,
		'hr' : 1,
		'hu' : 1,
		'id' : 1,
		'is' : 1,
		'it' : 1,
		'ja' : 1,
		'ka' : 1,
		'km' : 1,
		'ko' : 1,
		'ku' : 1,
		'lt' : 1,
		'lv' : 1,
		'mk' : 1,
		'mn' : 1,
		'ms' : 1,
		'nb' : 1,
		'nl' : 1,
		'no' : 1,
		'oc' : 1,
		'pl' : 1,
		'pt' : 1,
		'pt-br' : 1,
		'ro' : 1,
		'ru' : 1,
		'si' : 1,
		'sk' : 1,
		'sl' : 1,
		'sq' : 1,
		'sr' : 1,
		'sr-latn' : 1,
		'sv' : 1,
		'th' : 1,
		'tr' : 1,
		'tt' : 1,
		'ug' : 1,
		'uk' : 1,
		'vi' : 1,
		'zh' : 1,
		'zh-cn' : 1
	}
};